/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConnectFourS } from "./ConnectFourS";
export * as factories from "./factories";
export { ConnectFourS__factory } from "./factories/ConnectFourS__factory";
